name: drawscape_api
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - flask
  - flask-cors
  - svgwrite
  - numpy
  - python-dotenv  
  # - drawscape-factorio
  - gunicorn
  - boto3
  - psutil
  - pip:
    - flask[async]
